using Ical.Net;
using Ical.Net.CalendarComponents;
using Ical.Net.DataTypes;
using System.Runtime.Serialization;
using DotnetAgents.CalDav.Core.Internal.Ical;
using DotnetAgents.CalDav.Core.Models;
using Shouldly;
using Xunit;
using TaskItem = DotnetAgents.CalDav.Core.Models.TaskItem;
using CalDavTaskStatus = DotnetAgents.CalDav.Core.Models.TaskStatus;
using CalDavTaskPriority = DotnetAgents.CalDav.Core.Models.TaskPriority;

namespace DotnetAgents.CalDav.Core.Tests.Unit.Internal.Ical;

public class TaskItemMapperTests
{
    [Fact]
    public void FromTodo_CommonFields_MapsCorrectly()
    {
        // Arrange
        var todo = new Todo
        {
            Uid = "test-uid-123",
            Summary = "Buy groceries",
            Description = "Milk, eggs, bread",
            Priority = 1,
            Status = "NEEDS-ACTION",
        };
        todo.Due = new CalDateTime(2025, 8, 15, 17, 0, 0);
        todo.DtStart = new CalDateTime(2025, 8, 1, 9, 0, 0);

        // Act
        var task = TaskItemMapper.FromTodo(todo, etag: "\"etag-123\"", href: "/calendars/user/task.ics");

        // Assert
        task.Uid.ShouldBe("test-uid-123");
        task.Summary.ShouldBe("Buy groceries");
        task.Description.ShouldBe("Milk, eggs, bread");
        task.Priority.ShouldBe(CalDavTaskPriority.High); // Priority 1 = High
        task.Status.ShouldBe(CalDavTaskStatus.NeedsAction);
        task.ETag.ShouldBe("\"etag-123\"");
        task.Href.ShouldBe("/calendars/user/task.ics");
        task.Due.ShouldNotBeNull();
        task.Start.ShouldNotBeNull();
    }

    [Fact]
    public void FromTodo_NullUid_DefaultsToAutoGeneratedUid()
    {
        // Note: iCal.NET's Todo auto-generates a UID when null is set
        var todo = new Todo
        {
            Summary = "No UID task",
        };

        var task = TaskItemMapper.FromTodo(todo);

        // iCal.NET auto-generates a UID, so it won't be empty string
        task.Uid.ShouldNotBeNullOrEmpty();
    }

    [Fact]
    public void FromTodo_NullSummary_DefaultsToEmptyString()
    {
        var todo = new Todo
        {
            Uid = "uid-1",
        };

        var task = TaskItemMapper.FromTodo(todo);

        task.Summary.ShouldBe(string.Empty);
    }

    [Fact]
    public void FromTodo_PriorityMapping_MapsCorrectly()
    {
        // Priority 0 = None
        var task0 = TaskItemMapper.FromTodo(new Todo { Uid = "1", Priority = 0 });
        task0.Priority.ShouldBe(CalDavTaskPriority.None);

        // Priority 1-4 = High
        var task1 = TaskItemMapper.FromTodo(new Todo { Uid = "2", Priority = 1 });
        task1.Priority.ShouldBe(CalDavTaskPriority.High);
        var task4 = TaskItemMapper.FromTodo(new Todo { Uid = "3", Priority = 4 });
        task4.Priority.ShouldBe(CalDavTaskPriority.High);

        // Priority 5 = Medium
        var task5 = TaskItemMapper.FromTodo(new Todo { Uid = "4", Priority = 5 });
        task5.Priority.ShouldBe(CalDavTaskPriority.Medium);

        // Priority 6-9 = Low
        var task9 = TaskItemMapper.FromTodo(new Todo { Uid = "5", Priority = 9 });
        task9.Priority.ShouldBe(CalDavTaskPriority.Low);

        // Out of range (negative or > 9) = None
        var taskNeg = TaskItemMapper.FromTodo(new Todo { Uid = "6", Priority = -1 });
        taskNeg.Priority.ShouldBe(CalDavTaskPriority.None);
        var task99 = TaskItemMapper.FromTodo(new Todo { Uid = "7", Priority = 99 });
        task99.Priority.ShouldBe(CalDavTaskPriority.None);
    }

    [Fact]
    public void FromTodo_StatusMapping_MapsCorrectly()
    {
        var needsAction = TaskItemMapper.FromTodo(new Todo { Uid = "1", Status = "NEEDS-ACTION" });
        needsAction.Status.ShouldBe(CalDavTaskStatus.NeedsAction);

        var inProcess = TaskItemMapper.FromTodo(new Todo { Uid = "2", Status = "IN-PROCESS" });
        inProcess.Status.ShouldBe(CalDavTaskStatus.InProcess);

        var completed = TaskItemMapper.FromTodo(new Todo { Uid = "3", Status = "COMPLETED" });
        completed.Status.ShouldBe(CalDavTaskStatus.Completed);

        var cancelled = TaskItemMapper.FromTodo(new Todo { Uid = "4", Status = "CANCELLED" });
        cancelled.Status.ShouldBe(CalDavTaskStatus.Cancelled);

        // null status defaults to NeedsAction
        var nullStatus = TaskItemMapper.FromTodo(new Todo { Uid = "5" });
        nullStatus.Status.ShouldBe(CalDavTaskStatus.NeedsAction);

        // Unknown status defaults to NeedsAction
        var unknownStatus = TaskItemMapper.FromTodo(new Todo { Uid = "6", Status = "UNKNOWN" });
        unknownStatus.Status.ShouldBe(CalDavTaskStatus.NeedsAction);
    }

    [Fact]
    public void FromTodo_CategoriesWithCommas_SplitsCorrectly()
    {
        // Arrange
        var todo = new Todo
        {
            Uid = "cat-test",
            Categories = ["Work, Urgent", "Personal"],
        };

        // Act
        var task = TaskItemMapper.FromTodo(todo);

        // Assert - "Work, Urgent" should split into "Work" and "Urgent", plus "Personal"
        task.Categories.ShouldContain("Work");
        task.Categories.ShouldContain("Urgent");
        task.Categories.ShouldContain("Personal");
    }

    [Fact]
    public void FromTodo_NullCategories_ReturnsEmptyList()
    {
        var todo = new Todo { Uid = "no-cat" };
        todo.Categories = null!;

        var task = TaskItemMapper.FromTodo(todo);
        task.Categories.ShouldBeEmpty();
    }

    [Fact]
    public void FromTodo_NullDates_ReturnsNullDateOffsets()
    {
        var todo = new Todo { Uid = "no-dates" };

        var task = TaskItemMapper.FromTodo(todo);
        task.Due.ShouldBeNull();
        task.Start.ShouldBeNull();
        task.Completed.ShouldBeNull();
    }

    [Fact]
    public void FromTodo_WithRecurrenceRule_MapsRule()
    {
        var todo = new Todo
        {
            Uid = "recurring",
            RecurrenceRules = [new RecurrencePattern(FrequencyType.Daily, 1) { Count = 5 }],
        };

        var task = TaskItemMapper.FromTodo(todo);
        task.RecurrenceRule.ShouldNotBeNull();
        task.RecurrenceRule.ShouldContain("FREQ=DAILY");
    }

    [Fact]
    public void ToICalText_AndBack_RoundTripPreservesCommonFields()
    {
        // Arrange
        var original = new TaskItem
        {
            Uid = "roundtrip-uid",
            Summary = "Round trip task",
            Description = "Test description",
Priority = CalDavTaskPriority.High,
        Status = CalDavTaskStatus.NeedsAction,
            Due = new DateTimeOffset(2025, 8, 15, 17, 0, 0, TimeSpan.Zero),
            Categories = ["Work"],
        };

        // Act - serialize to iCal text
        var icalText = TaskItemMapper.ToICalText(original);

        // Assert - should be valid iCalendar
        icalText.ShouldNotBeNullOrEmpty();
        icalText.ShouldContain("BEGIN:VCALENDAR");
        icalText.ShouldContain("BEGIN:VTODO");
        icalText.ShouldContain("SUMMARY:Round trip task");

        // Act - parse it back
        var parsed = TaskItemMapper.FromICalText(icalText, etag: "etag-rt");

        // Assert - round trip preserves key fields
        parsed.Count.ShouldBe(1);
        parsed[0].Uid.ShouldBe("roundtrip-uid");
        parsed[0].Summary.ShouldBe("Round trip task");
        parsed[0].Priority.ShouldBe(CalDavTaskPriority.High);
        parsed[0].ETag.ShouldBe("etag-rt");
    }

    [Fact]
    public void ToTodo_GeneratesUid_WhenEmpty()
    {
        var task = new TaskItem
        {
            Uid = "",
            Summary = "No UID task",
        };

        var todo = TaskItemMapper.ToTodo(task);
        todo.Uid.ShouldNotBeNullOrEmpty();
    }

    [Fact]
    public void ToTodo_PreservesUid_WhenProvided()
    {
        var task = new TaskItem
        {
            Uid = "existing-uid",
            Summary = "Task with UID",
        };

        var todo = TaskItemMapper.ToTodo(task);
        todo.Uid.ShouldBe("existing-uid");
    }

    [Fact]
    public void ToTodo_MapsPriorityCorrectly()
    {
        var highTask = new TaskItem { Uid = "1", Priority = CalDavTaskPriority.High };
        TaskItemMapper.ToTodo(highTask).Priority.ShouldBe(1);

        var mediumTask = new TaskItem { Uid = "2", Priority = CalDavTaskPriority.Medium };
        TaskItemMapper.ToTodo(mediumTask).Priority.ShouldBe(5);

        var lowTask = new TaskItem { Uid = "3", Priority = CalDavTaskPriority.Low };
        TaskItemMapper.ToTodo(lowTask).Priority.ShouldBe(9);

        var noneTask = new TaskItem { Uid = "4", Priority = CalDavTaskPriority.None };
        TaskItemMapper.ToTodo(noneTask).Priority.ShouldBe(0);
    }

    [Fact]
    public void ToTodo_MapsStatusCorrectly()
    {
        var needsAction = new TaskItem { Uid = "1", Status = CalDavTaskStatus.NeedsAction };
        TaskItemMapper.ToTodo(needsAction).Status.ShouldBe("NEEDS-ACTION");

        var inProcess = new TaskItem { Uid = "2", Status = CalDavTaskStatus.InProcess };
        TaskItemMapper.ToTodo(inProcess).Status.ShouldBe("IN-PROCESS");

        var completed = new TaskItem { Uid = "3", Status = CalDavTaskStatus.Completed };
        TaskItemMapper.ToTodo(completed).Status.ShouldBe("COMPLETED");

        var cancelled = new TaskItem { Uid = "4", Status = CalDavTaskStatus.Cancelled };
        TaskItemMapper.ToTodo(cancelled).Status.ShouldBe("CANCELLED");
    }

    [Fact]
    public void ToTodo_WithCategories_SetsCategories()
    {
        var task = new TaskItem
        {
            Uid = "cat-task",
            Summary = "Categorized",
            Categories = ["Work", "Personal"],
        };

        var todo = TaskItemMapper.ToTodo(task);
        todo.Categories.ShouldContain("Work");
        todo.Categories.ShouldContain("Personal");
    }

    [Fact]
    public void ToTodo_WithRecurrenceRule_SetsRecurrenceRules()
    {
        var task = new TaskItem
        {
            Uid = "recur-task",
            Summary = "Recurring",
            RecurrenceRule = "FREQ=WEEKLY;COUNT=10",
        };

        var todo = TaskItemMapper.ToTodo(task);
        todo.RecurrenceRules.ShouldNotBeNull();
        todo.RecurrenceRules.Count.ShouldBe(1);
    }

    [Fact]
    public void ToTodo_NullRecurrenceRule_NoRecurrenceRules()
    {
        var task = new TaskItem
        {
            Uid = "no-recur",
            Summary = "One-time",
            RecurrenceRule = null,
        };

        var todo = TaskItemMapper.ToTodo(task);
        // RecurrenceRules should be null or empty when no recurrence is set
        (todo.RecurrenceRules == null || todo.RecurrenceRules.Count == 0).ShouldBeTrue();
    }

    [Fact]
    public void FromICalText_InvalidText_ThrowsSerializationException()
    {
        Should.Throw<SerializationException>(() => TaskItemMapper.FromICalText("not-valid-ical"));
    }

    [Fact]
    public void FromICalText_ThrowsOnMalformedInput()
    {
        const string malformed = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VTODO\r\nUID:test-uid\r\nSUMMARY:Broken";

        Should.Throw<SerializationException>(() => TaskItemMapper.FromICalText(malformed));
    }

    [Fact]
    public void FromICalText_EmptyCalendar_ReturnsEmptyList()
    {
        // Arrange
        var icalText = "BEGIN:VCALENDAR\r\nEND:VCALENDAR";

        // Act
        var result = TaskItemMapper.FromICalText(icalText);

        // Assert
        result.ShouldBeEmpty();
    }
}
